using ServiceAxis.Domain.Common;
using ServiceAxis.Domain.Entities.Assignment;
using ServiceAxis.Domain.Entities.Platform;

namespace ServiceAxis.Domain.Entities.Records;

/// <summary>
/// A single record row in any dynamic table.
/// Instead of one SQL table per business entity, all platform records
/// (Incidents, Assets, Change Requests, etc.) are stored here.
/// The actual field values live in <see cref="RecordValue"/>.
/// </summary>
public class PlatformRecord : BaseEntity
{
    /// <summary>Which dynamic table this record belongs to.</summary>
    public Guid TableId { get; set; }
    public SysTable Table { get; set; } = null!;

    /// <summary>
    /// Human-readable auto-number (e.g. INC0001, CHG0042).
    /// Generated by the record engine on creation.
    /// </summary>
    public string? RecordNumber { get; set; }

    /// <summary>Current state/status of the record (driven by workflow).</summary>
    public string State { get; set; } = "new";

    /// <summary>
    /// Display value — denormalised summary for list views.
    /// Usually the value of the primary text field (e.g. the Incident title).
    /// </summary>
    public string? ShortDescription { get; set; }

    /// <summary>Priority (1=Critical, 2=High, 3=Medium, 4=Low). Null = not applicable.</summary>
    public int? Priority { get; set; }

    /// <summary>User (IdentityUserId) the record is assigned to.</summary>
    public string? AssignedToUserId { get; set; }

    /// <summary>Assignment group the record belongs to.</summary>
    public Guid? AssignmentGroupId { get; set; }

    /// <summary>Tenant ownership.</summary>
    public Guid? TenantId { get; set; }

    /// <summary>Whether the record has been soft-deleted.</summary>
    public bool IsDeleted { get; set; } = false;

    /// <summary>UTC timestamp when the record was resolved/closed.</summary>
    public DateTime? ResolvedAt { get; set; }

    /// <summary>UTC timestamp when the record was closed.</summary>
    public DateTime? ClosedAt { get; set; }

    /// <summary>
    /// FK to the current <see cref="RecordStateDefinition"/> for this record.
    /// Null until a lifecycle is configured for the table.
    /// Always mutated via <c>IStateMachineService</c> — never set directly.
    /// </summary>
    public Guid? CurrentStateId { get; set; }
    public RecordStateDefinition? CurrentState { get; set; }

    /// <summary>UTC timestamp of the last state transition.</summary>
    public DateTime? StateChangedAt { get; set; }

    // Navigation
    public ICollection<RecordValue> Values { get; set; } = new List<RecordValue>();
    public ICollection<RecordAudit> Audits { get; set; } = new List<RecordAudit>();
}
